### ISSUE TITLE
HTML body

### ISSUE THREAD

**Issue by Vinit-Sapiens** [cinotify/github-action#15]
I'd love to know how can I send the HTML as an email body.

**Comment by jshawl** [comment]
@Vinit-Sapiens I think this is doable. What do you think about something like this:

```yaml
uses: cinotify/github-action@main
with:
  to: 'example@example.com'
  subject: 'building main'
  body: '<h1>This is a notification from GitHub actions.</h1>' # html here
  type: 'text/html' # defaults to text/plain
  attachment: 'artifacts.zip'
```

**Comment by Vinit-Sapiens** [comment]
Thank you, Let me try

**Comment by Vinit-Sapiens** [comment]
It is not working, sending mail as plain test only. @jshawl 
 ```
- name: Send Allure Regression Report Email
        uses: cinotify/github-action@main
        if: always() && !cancelled()
        continue-on-error: true
        with:
          to: 'xyz@abc.com'
          subject: 'Allure Regression Report for ${{ github.event.client_payload.PORTAL_TYPE }} Portal | Run ${{ github.run_number }}'
          type: 'text/html'
          body: |
            Hi Team,
            <h1>This is a notification from GitHub actions.</h1>
```

![image](https://github.com/cinotify/github-action/assets/125962252/0e494691-a062-4df3-b107-7860d2f11c5c)
