### ISSUE TITLE
Actions doesn't work

### ISSUE THREAD

**Issue by jayayy** [cinotify/github-action#3]
I have used the action as follows: 
```
    - name: CINotify Email
    # You may pin to the exact commit or the version.
    # uses: cinotify/github-action@d99e3149178b27572a58ace227621c333884e3fb
      uses: cinotify/github-action@v1.1.0
      with:
        # Recipient email address
        to: mehta.jay223@gmail.com
        # Email subject
        subject: Your PR has been merged
        # Email body
        body: Enjoy your day off!
   - run: echo ${{steps.serve.outputs.status }}
```
![image](https://user-images.githubusercontent.com/87470487/163805736-ebb2ca70-b750-45ad-a5cc-9c6bd692376c.png)

Can you tell me why am I unable to receive a mail? I checked in spam and trash folders as well.
